### ISSUE TITLE
Function MAKE-OBJECT does not exist.

### ISSUE THREAD

**Issue by phoe** [hanshuebner/bknr-datastore#12]
The BKNR.DATASTORE manual that I found on the Internet references function MAKE-OBJECT as a way to create persistent objects.

The symbol is not present in the current Quicklisp version of BKNR.DATASTORE.
Additionally, https://github.com/hanshuebner/bknr-datastore/blob/9efe61a4f4c6244f2bec6a6192c52b967810ba07/src/data/TODO#L18 mentions removing this function in favor of MAKE-INSTANCE.

Did this switch/removal already happen? If yes, you might want to remove this line from TODO.

**Comment by hanshuebner** [comment]
MAKE-OBJECT has been removed because MAKE-INSTANCE is better.  Patches are
welcome.

2017-01-24 12:37 GMT-05:00 Michał Herda <notifications@github.com>:
