### ISSUE TITLE
store a slot of type local-time:timestamp

### ISSUE THREAD

**Issue by admich** [hanshuebner/bknr-datastore#13]
I want to store an object with a slot of type local-time:timestamp as:

-----------
(define-persistent-class class-with-date ()
  ((datetime :update)))

(with-transaction ()
  (make-instance 'class-with-date :datetime (local-time:now)))

----------
I use the following code:
 
(in-package :bknr.datastore)

(defmethod encode-object ((object local-time:timestamp) stream)
  (%write-tag #\t stream)
  (%encode-integer (local-time:timestamp-to-universal object) stream))

(defmethod decode-object ((tag (eql #\t)) stream)
  (local-time:universal-to-timestamp (%decode-integer stream)))

---------------
1) Is this the correct method to obtain what I want?
2) I have choosed #\t as tag char for local-time:timestamp. Is it possible future conflicts? Is there  a standard policy to choose a tag-char for user-defined type?

**Comment by hanshuebner** [comment]
I would use an upper-case letter for user-defined types, but that is just a matter of taste.  Other than that, your solution looks good to me.  You'll have to determine correctness yourself.  I'd not be worried about the future, there have not been any changes in bknr.datastore for many years, so it can be considered stable.
