### ISSUE TITLE
Link to website documentation timing out

### ISSUE THREAD

**Issue by CodyReichert** [hanshuebner/bknr-datastore#15]
Hey there, the website pages for the license file and documentation are timing out:
- http://bknr.net/html/home.html
- http://bknr.net/html/license.html

We link to these from the [awesome-cl](https://github.com/CodyReichert/awesome-cl) page so I wanted to see if this is something you will fix, or if we should link somewhere else for the license? https://awesome-cl.com/#persistent-object-databases

**Comment by hanshuebner** [comment]
I've given up the bknr.net domain name and have no current plans to re-host the documentation.  I would probably not be all that difficult to host it on github pages, but as I am not currently working in Common Lisp, I'm not all that content to put time into this.  If there are interested people, I'll gladly move the repository to a separate organization and give whoever wants it write access to that.

**Comment by hanshuebner** [comment]
I've added a license file: https://github.com/hanshuebner/bknr-datastore/blob/master/license.txt

**Comment by CodyReichert** [comment]
Thank you!
